### ISSUE TITLE
pip package of generinator-rats installs an older version than what in your git repository

### ISSUE THREAD

**Issue by RavivBarzilay** [renatahodovan/generinator-rats#1]
Although the documentation points you to simply install everything via pip,
the pip version is broken and doesnt work at all.

this is also the case for fuzzinator, which i think that there are different class names between versions.
anyways i ended up installing the whole suite thru git (picireny picire fuzzinator etc) just to be sure, and for now it seems to be working

Thanks

**Comment by renatahodovan** [comment]
@RavivBarzilay Could you paste the error message you received, please? I still can install it via pip without any error messages.
My only guess is that the antlr jar is missing. In this case the error message would say that the loading of parser modules failed. To solve this problem you have to run the `generinator-rats-install-antlr4` script or download the jar manually and specify via the `--antlr` argument. (I missed it from the README, but will release a new version soon where this is not needed at all.)
Furthermore, if you experience further issues in fuzzinator or the reducers, please report them, too :)

**Comment by RavivBarzilay** [comment]
@renatahodovan  Hi.. It might take me some time since I have a weird setup.
and I ended up cloning it and running setup.py, and it works now

And I will let you know on issues I find :)

**Comment by RavivBarzilay** [comment]
oops I don't know if i meant to close it

**Comment by RavivBarzilay** [comment]
okay, the error i get is
"Exception while loading parser modules: list index out of range"

but after running generinator-rats-install-antlr4 it works

thanks.
